### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by OshanJayawardena** [Tian0426/CL-HAR#1]
Can't find models.py in models

**Comment by Tian0426** [comment]
Hi @OshanJayawardana, please refer to frameworks.py instead. We change the name to differentiate the file with the 'models' folder. Already update the filename in README.

**Comment by OshanJayawardana** [comment]
> Hi @OshanJayawardana, please refer to frameworks.py instead. We change the name to differentiate the file with the 'models' folder. Already update the filename in README.

**Comment by OshanJayawardena** [comment]
@Tian0426 Thank you very much for the quick response. I found the frameworks.py but I wasn't able to find the implementation of simsiam model.

**Comment by Tian0426** [comment]
SimSiam and BYOL share the same framework implementation, while their parameter setups have some differences. You may want to check up the ```setup()``` function in ```trainer.py``` for more details, where the default hyper-parameters for each model are specified at the beginning.

**Comment by OshanJayawardena** [comment]
Thank you very much
