### ISSUE TITLE
Question about data preprocessing

### ISSUE THREAD

**Issue by OshanJayawardena** [Tian0426/CL-HAR#2]
What are the data preprocessing methods you use for pre-processing UCI HAR data, except the sliding window?

**Comment by Hangwei12358** [comment]
Hi @OshanJayawardana,

Standard normalization and sliding window methods are applied for data pre-processing. Please refer to `./data_preprocess/data_preprocess_ucihar.py`. Thanks.

**Comment by OshanJayawardena** [comment]
Thank you very much
