### ISSUE TITLE
How to download datasets?

### ISSUE THREAD

**Issue by yhhhli** [Tian0426/CL-HAR#3]
Hi, very impressive framework. 

However, could you please tell me how to download the datasets you used in the paper?

Thanks.

**Comment by Hangwei12358** [comment]
Hi @yhhhli,

Thank you for your comments. Datasets can be downloaded from the following sites. 

[UCIHAR](https://archive.ics.uci.edu/ml/datasets/human+activity+recognition+using+smartphones)

[SHAR](http://www.sal.disco.unimib.it/technologies/unimib-shar/)

[HHAR](http://archive.ics.uci.edu/ml/datasets/heterogeneity+activity+recognition)

The downloaded datasets can be put under `./data/` folder, and then our code can do the data preprocessing. Hope this helps!

**Comment by yhhhli** [comment]
Thank you very much!

Also, I have another question. Would it be possible to open-source the supervised learning baseline? It's okay if it is too complicated to update the code. Some hints on the implementation are much appreciated. Thanks again!

**Comment by Tian0426** [comment]
Hi @yhhhli, we have uploaded ```main_supervised_baseline.py``` which could be used to train encoder networks in supervised setting. Hope it helps!

**Comment by yhhhli** [comment]
Thank you!
