### ISSUE TITLE
Report a Bug in main_supervised_baseline.py

### ISSUE THREAD

**Issue by xiqxin1** [Tian0426/CL-HAR#7]
Hi Tian,

Thank you very much for sharing the code.

In lines 167-168, you add: 
# trgs = torch.cat((trgs, target))#
# feats = torch.cat((feats, features), 0)#
which makes the length of trgs become two times as prds when calculating the confusion_matrix(in line 175). I'm not sure if it is correct.

**Comment by Tian0426** [comment]
Hi @xiqxin1,

Thank you for pointing this out. You can delete these two lines in your code. Correction has been made in the repo!

**Comment by xiqxin1** [comment]
Thank you!
